### ISSUE TITLE
Swipes not working in the browser

### ISSUE THREAD

**Issue by bladecell** [Nemuritor01/css-swipe-card#5]
Hi, for some reason, the swiping to next card does not work for me on browser, only button navigation. On mobile the swiping works fine. Is it config issue?

```
type: custom:css-swipe-card
cardId: mainswipecard
template: slider-horizontal
auto_height: true
pagination: true
card_gap: 2rem
height: 10rem
cards:
  - type: custom:button-card
    entity: sensor.hall_temperature
    template: sensor_graph
    variables:
      hr_to_show: 36
      pts_per_hr: 0.3
  - type: custom:button-card
    entity: sensor.total_power_w
    template: sensor_graph
  - type: sensor
    entity: sensor.hall_temperature
    hours_to_show: 12
    detail: 1
    graph: line
    icon: none
    card_mod:
      class: graph
```
